# $PROJECT_ID resolves to the current project's ID
# ${_SERVICE} must be provided via --substitutions=_SERVICE=my-service-name argument.

# gcloud builds submit --substitutions _SERVICE=service-name

# See the link below for details on setting default values for substitutions
# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values

# See this awesome example of how to run unit tests and test coverage using Cloud Build
# https://threedots.tech/post/running-integration-tests-on-google-cloud-build/ 

# Service URL: https://dfcx-vocaptcha-63ietzwyxq-uk.a.run.app

steps:
  
- id: docker-build-push-service
  waitFor: ['-']
  dir: cr-speaker-id
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - | 
    docker build -t gcr.io/$PROJECT_ID/${_SERVICE} .
    docker push gcr.io/$PROJECT_ID/${_SERVICE}

- id: gcloud-run-deploy-backend-processor
  waitFor: ['docker-build-push-service']
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args: 
  - -c
  - | 
    gcloud run deploy ${_SERVICE} \
      --project $PROJECT_ID \
      --image gcr.io/$PROJECT_ID/${_SERVICE} \
      --update-secrets DB_HOST=_DB_HOST:1 \
      --update-secrets DB_PORT=_DB_PORT:1 \
      --update-secrets DB_USER=_DB_USER:1 \
      --update-secrets DB_PASS=_DB_PASS:1 \
      --update-secrets DB_NAME=_DB_NAME:1 \
      --update-secrets DB_CNST=_DB_CNST:1 \
      --timeout 15m \
      --region ${_REGION} \
      --no-cpu-throttling \
      --vpc-connector ${_VPC_CONNECTOR} \
      --platform managed \
      --min-instances 0 \
      --max-instances 5 \
      --allow-unauthenticated

options:
  pool:
    name: projects/vocal-etching-343420/locations/${_REGION}/workerPools/${_POOL}

substitutions:
  _SERVICE: py-speaker-id-adv
  _VPC_CONNECTOR: svpca-vpc-sb-dialogflow
  _REGION: us-central1
  _POOL: cb-pool-1

# # Build step for testing.  Removed temporarily.  
# - id: application-testing
#   waitFor: ['docker-build-push-service']
#   dir: cr-speaker-id
#   name: gcr.io/cloud-builders/docker
#   entrypoint: bash
#   args:
#   - -c
#   - |
#     echo "Hello World!"
#     docker run -it --rm gcr.io/$PROJECT_ID/${_SERVICE} /bin/bash
#     pytest -s
#   env:
#   - DB_HOST=$$_DB_HOST
#   - DB_PORT=$$_DB_PORT
#   - DB_USER=$$_DB_USER
#   - DB_PASS=$$_DB_PASS
#   - DB_NAME=$$_DB_NAME
#   - DB_CNST=postgresql+psycopg2://$$_DB_USER:$$_DB_PASS@$$_DB_HOST:$$_DB_PORT/$$_DB_NAME
#   secretEnv: ['_DB_HOST', '_DB_PORT', '_DB_USER', '_DB_PASS', '_DB_NAME']